### ISSUE TITLE
a request

### ISSUE THREAD

**Issue by KunyuNi** [wangkechun/go-by-example#11]
您好，我是一名研一的学生，未来想从事go语言开发，因为之前信息闭塞的原因，没能够参加，字节跳动的第三届青训营。自己在自学的过程中，也遇到很多问题，得知有直播回放后，冒昧请问，能否从您那里获取，谢谢!

**Comment by Eminem-x** [comment]
可以通过内网访问 `tech`，而后搜青训营就可以找到，不知道是否合规，就不贴链接了。

**Comment by mo3et** [comment]
不知道你是否还需要，现在可以通过参加青训营，获得掘金的会员，掘金的字节内部课就是了。
如果错过了也可以自己开个掘金会员去看视频。
如果看到了请麻烦 Close 这个 issue

**Comment by KunyuNi** [comment]
谢谢
